### ISSUE TITLE
Align defaults for maps and sequences

### ISSUE THREAD

**Issue by dchelimsky** [nubank/matcher-combinators#108]
The default matcher for a `map` is `embeds` (tolerant).
The default matcher for a `seq` is `equals` (strict).

This is confusing, especially when you have sequences within a map, e.g.

```clojure
(match
 {:account/owners [{:person/first-name "David"}]}
 {:account/balance 37.42
  :account/owners  [{:person/first-name "David"
                     :person/last-name "Chelimsky"}
                    {:person/first-name "Phillip"}]})
```

By default, `match` is ignores `:account/balance` and `:person/last-name`, but fails because there are 2 elements in the `:account/owners` seq instead of just 1. This forces you to write this:

``` clojure
(match
 {:account/owners (matchers/embeds [{:person/first-name "David"}])}
 {:account/balance 37.42
  :account/owners  [{:person/first-name "David"
                     :person/last-name "Chelimsky"}
                    {:person/first-name "Phillip"}]})
```

Recommendation: make the default for sequences `embeds`.

Considerations: this should not cause any existing tests to fail, because the constraint is becoming less restrictive, however it would mean that when users really care about the seq size being strict, future changes to implementation could lead to false positives.

**Comment by philomates** [comment]
The approach that I've been taking so far with choosing default matchers is to choose the most commonly used ones to avoid as much as possible the need to annotate subelements of a data-structure. In my experience, `embeds` on lists is rarely used, and so the default of `equals` both aligns with common usage and offers stricter matching semantics.

I do agree that having different data-structures default to different matching semantics is confusing and takes getting used to. I also think that the benefits of matching most common usage patterns outweigh this. I sorta see it like the approach to boolean punning that clojure takes, or the pattern in clojure to pass around a map with a bunch of stuff but use clojure.spec to declare the parts you care about (which I actually haven't fully embraced yet, but there is time :smile:)

Although it might not break existing tests, I see this as a substantial breaking change because it changes quite substantially the behavior of the library.

For strict matching all around, one can use [`match-equals` instead of `match`](https://github.com/nubank/matcher-combinators/#overriding-default-matchers). Do you think making more use of that would work?

**Comment by dchelimsky** [comment]
Agree re: the change being breaking. If we were to make this change, we'd need to do it in a way that leaves the existing behavior in place and offer alternatives via config (strict/tolerant), new namespaces, etc. That would definitely warrant a philosophical re-think and a holistic approach/rollout. I'll put some thoughts together on this.

Disagree re: philosophy. We consider the Robustness principle (a.k.a. Postel's Law) in other contexts, and I think that's something we want to be consistent about. The first example I gave above is more aligned with that. For me, that outweighs common use.

**Comment by philomates** [comment]
an additional consideration is the fact that `embeds` for sequences is (currently) much slower than `equals` (https://github.com/nubank/matcher-combinators/issues/106) so that should be factored into the impacts of such a shift.

**Comment by dchelimsky** [comment]
Closing this. Added https://github.com/nubank/matcher-combinators/issues/113 to focus on documentation.
