### ISSUE TITLE
Issue with `contains`

### ISSUE THREAD

**Issue by caioaao** [nubank/matcher-combinators#43]
I have this weird behavior:

```clojure
(defn ok-function []
  [{:a 1, :zz 7}
   {:b 2, :zz 7}
   {:c 3, :zz 7}])

(fact "test should pass"
  (ok-function) => (match (contains [{:b 2}])))

(defn nok-function []
  [])

(fact "test should not pass"
  (nok-function) => (match (contains [{:b 2}])))
```

Both tests are passing. Version is `0.2.8`

**Comment by phillipm** [comment]
Hey @caioaao, `contains` is a built-in midje checker, whereas this lib seeks to replace usage of such built-in checkers with the `match` checker and [various compose-able matchers combinators](https://github.com/nubank/matcher-combinators#matchers).
Can you get the same behavior by making use of a matcher combinator instead of a midje checker within the `match`?

For instance:
```clojure
(fact
  (ok-function) => (match (embeds [(embeds {:b 2})])))
```

which is the same as the following via the [default matchers](https://github.com/nubank/matcher-combinators#default-matchers)

```clojure
(fact
  (ok-function) => (match (embeds [{:b 2})]))
```

**Comment by caioaao** [comment]
ahhh, thanks @phillipm . For some reason I thought it should be compatible with midje's built-in checkers

**Comment by phillipm** [comment]
We could explore making them compatible but since they do very similar things, but with slightly different behavior, I think it would be best to keep them separate and re-implement any functionality provided by midje checkers as built-in matcher combinators

**Comment by caioaao** [comment]
Completely agree. Just a confusion on my part. Thanks!
